Initial Prototype of how changes related to file upload would look like.
Shurtu-gal/localstorage-prototype-amplication pull request #1
Opened 2024-03-13 20:29 UTC by Shurtu-gal

2024-03-18 11:23 UTC, overbit commented on server/src/storage/core/types.core.ts
> +  id?: string;
is this necessary with the `uuid` already present? 
Not a complain, just trying to understand the reasoning behind this property

2024-03-18 11:23 UTC, overbit commented on server/src/storage/core/storage.core.service.ts
> +  deleteFile(file: StorageFileCore): Promise<boolean>;
Defining this types as generics that extends `StorageFileCore` instead of just relying on mapping would make the solution more type safe here.
i.e.
```suggestion
  uploadFile<T extends StorageFileCore>(file: FileUpload): Promise<T>;
  downloadFile<T extends StorageFileCore>(file: T): Promise<StreamableFile>;
  deleteFile<T extends StorageFileCore>(file: T): Promise<boolean>;
```

2024-03-18 11:23 UTC, overbit commented on server/src/storage/core/storage.core.service.ts
> +    protected readonly localStorageProvider: LocalStorageService,
What do you think about having `LocalStorageProvider` extending from an abstract class `StorageServiceCore` instead of having 2 class initialised here (StorageServiceCore andLocalStorageProvider)?
On the benefit side, it won't require switch statements to chose the correct provider as the service in charge, like userService, will already inject the needed StorageProvider dependency

2024-03-18 11:23 UTC, overbit commented on server/src/storage/storage.module.ts
> +  exports: [StorageService, LocalStorageService],
In the current implementation, `LocalStorageService` is only injected into StorageCore service so this module doesn't need to export it.
```suggestion
  exports: [StorageService],
```

2024-03-18 11:23 UTC, overbit commented on server/src/user/user.resolver.ts
> +import { StorageService } from "src/storage/storage.service";
probably this is a missed leftover. We can safely remove it, right?

2024-03-18 11:23 UTC, overbit commented on server/src/user/base/user.service.base.ts
> +    const profilePicture = await this.storageService.uploadFile(file, ProvidersEnum.LOCAL, ["image"], 1000000);
I'd recommend to make the max_size easily changeable without changes to this base file.

2024-03-26 11:34 UTC, overbit requested changes

2024-03-26 11:34 UTC, overbit commented on server/src/storage/base/storage.service.base.ts
> +  async verifyFile(file: FileUpload, extensions: (FileExtensionEnum | string)[], maxSize?: number): Promise<void> {
This method can be defined as `protected` instead of public as only the provider would need to call it

2024-03-26 11:34 UTC, overbit commented on server/src/storage/base/storage.service.base.ts
> +  async checkFileSize(file: FileUpload, maxSize: number): Promise<number> {
This method can be defined as `protected` instead of public as only the provider would need to call it

2024-03-26 11:34 UTC, overbit commented on server/src/storage/base/storage.service.base.ts
> +  getMimeType(file: StorageFileBase) {
This method can be defined as `protected` instead of public as only the provider would need to call it

2024-03-26 11:34 UTC, overbit commented on server/src/storage/base/storage.service.base.ts
> +  abstract deleteFile<T extends StorageFileBase>(file: T): Promise<boolean>;
love this!

2024-03-26 11:34 UTC, overbit commented on server/src/storage/base/storage.types.ts
> +}
This enum is probably not needed anymore as per use of the mime lib

2024-03-26 16:40 UTC, Shurtu-gal commented on server/src/storage/base/storage.types.ts
> +}
No, this is for a different purpose altogether and is used for verification of files getting uploaded by checking if it matches any of the allowed types.

2024-04-16 20:43 UTC, Shurtu-gal commented
Closing this as its not needed anymore.

2024-04-16 20:43 UTC, closed without merging